"""“3”

Revision ID: 58e714b5277e
Revises: ca202bf13c04
Create Date: 2024-11-18 13:10:08.463347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58e714b5277e'
down_revision: Union[str, None] = 'ca202bf13c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE statustypes ADD VALUE IF NOT EXISTS 'ASSESSED_FIT';")
    op.execute("ALTER TYPE statustypes ADD VALUE IF NOT EXISTS 'ASSESSED_HOLD';")
    op.execute("ALTER TYPE statustypes ADD VALUE IF NOT EXISTS 'ASSESSED_UNFIT';")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: Enum values are not critical. If critical, write downgrade.
    pass
    # ### end Alembic commands ###
