"""1

Revision ID: bdd2c2ec70eb
Revises: 
Create Date: 2024-11-11 18:12:08.464404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdd2c2ec70eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('SENIOR_PRODUCT_ENGINEER', name='roletypes'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETE', 'FAILED', name='statustypes'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('base_requirement_satisfaction_score', sa.Integer(), nullable=True),
    sa.Column('exceptional_considerations', sa.String(), nullable=True),
    sa.Column('fitness_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.drop_table('resume')
    # ### end Alembic commands ###
